# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cf40343f251ee2640bee4134458c59d4c2bb1edbecc5c951c60242ec47240e51af6f18e9ac370402c92439fcb10e6303f735829d0004e603e2e441068375ed5

test:
  secret_key_base: c132f8109078c5f4c209f6cb487ad4aea11244b4cef3df8952d6a5739777eb99b3302068b502e46436bc736003b90aee4aab36e0c45bfd6b1569f622f539a49b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
